HardpointDisplacementToMirrorPositionTablePath: Tables/HardpointDisplacementToMirrorPositionTable.csv
MirrorPositionToHardpointDisplacementTablePath: Tables/MirrorPositionToHardpointDisplacementTable.csv
MicrometersPerStep: 0.0607
MicrometersPerEncoder: 0.2442
HPEncoderOffsets: [29897, 30786, 53315, 61621, -21824, 35572]
HardpointMeasuredForceFaultHigh: 2400
HardpointMeasuredForceFaultLow: -2200
HardpointMeasuredForceFSBWarningHigh: 100
HardpointMeasuredForceFSBWarningLow: -100
HardpointMeasuredForceWarningHigh: 1200
HardpointMeasuredForceWarningLow: -1100
AirPressureFaultHigh: 127
AirPressureFaultLow: 110
AirPressureFaultLowRaising: 100
