AirControllerSettings:
  FaultOnCommandOutputMismatch: On
  FaultOnCommandSensorMismatch: On
  ValveTransitionTimeout: 40
DisplacementSettings:
  FaultOnSensorReportsInvalidCommand: On
  FaultOnSensorReportsCommunicationTimeoutError: On
  FaultOnSensorReportsDataLengthError: On
  FaultOnSensorReportsNumberOfParametersError: On
  FaultOnSensorReportsParameterError: On
  FaultOnSensorReportsCommunicationError: On
  FaultOnSensorReportsIDNumberError: On
  FaultOnSensorReportsExpansionLineError: On
  FaultOnSensorReportsWriteControlError: On
  FaultOnResponseTimeoutError: On
  FaultOnInvalidLength: On
  FaultOnInvalidResponse: On
  FaultOnUnknownCommand: On
  FaultOnUnknownProblem: On
InclinometerSettings:
  FaultOnResponseTimeout: On
  FaultOnInvalidCRC: On
  FaultOnUnknownAddress: On
  FaultOnUnknownFunction: On
  FaultOnInvalidLength: On
  FaultOnSensorReportsIllegalDataAddress: On
  FaultOnSensorReportsIllegalFunction: On
  FaultOnUnknownProblem: On
InterlockSettings:
  FaultOnHeartbeatStateOutputMismatch: On
  FaultOnAuxPowerNetworksOff: On
  FaultOnThermalEquipmentOff: On
  FaultOnAirSupplyOff: On
  FaultOnCabinetDoorOpen: On
  FaultOnTMAMotionStop: On
  FaultOnGISHeartbeatLost: On
ForceControllerSettings:
  FaultOnSafetyLimit: On
  FaultOnXMomentLimit: On
  FaultOnYMomentLimit: On
  FaultOnZMomentLimit: On
  FaultOnNearNeighborCheck: On
  FaultOnMagnitudeLimit: On
  FaultOnFarNeighborCheck: On
  FaultOnElevationForceClipping: On
  FaultOnAzimuthForceClipping: On
  FaultOnThermalForceClipping: On
  FaultOnBalanceForceClipping: On
  FaultOnAccelerationForceClipping: On
  FaultOnActiveOpticNetForceCheck: On
  FaultOnActiveOpticForceClipping: On
  FaultOnStaticForceClipping: On
  FaultOnOffsetForceClipping: On
  FaultOnVelocityForceClipping: On
  FaultOnForceClipping: On
PositionControllerSettings:
  FollowingErrorPercentage: 50
  FaultNumberOfFollowingErrors: 10
  FaultOnUnstableCount: 100
CellLightSettings:
  FaultOnOutputMismatch: On
  FaultOnSensorMismatch: On
PowerControllerSettings:
  FaultOnPowerNetworkAOutputMismatch: On
  FaultOnPowerNetworkBOutputMismatch: On
  FaultOnPowerNetworkCOutputMismatch: On
  FaultOnPowerNetworkDOutputMismatch: On
  FaultOnAuxPowerNetworkAOutputMismatch: On
  FaultOnAuxPowerNetworkBOutputMismatch: On
  FaultOnAuxPowerNetworkCOutputMismatch: On
  FaultOnAuxPowerNetworkDOutputMismatch: On
RaiseOperationSettings:
  FaultOnTimeout: On
LowerOperationSettings:
  FaultOnTimeout: On
AccelerometerSettings:
  FaultOnSampleTimeout: On
  FaultOnAngularAccelerationX: On
  FaultOnAngularAccelerationY: On
  FaultOnAngularAccelerationZ: On
ILCSettings:
  FaultOnCommunicationTimeout: On
  CommunicationTimeoutCountThreshold: 3
  CommunicationTimeoutPeriod: 5
  FaultOnForceActuatorFollowingError: On
  ForceActuatorFollowingErrorCountThreshold: 50
  ForceActuatorFollowingErrorPeriod: 50
  FaultOnHardpointActuatorLoadCellError: On
  FaultOnHardpointActuatorMeasuredForce: On
  HardpointActuatorMeasuredForceCountThreshold: 50
  HardpointActuatorMeasuredForcePeriod: 50
  FaultOnAirPressure: On
  AirPressureCountThreshold: 50
  AirPressurePeriod: 50
ForceActuatorFollowingError:
  FaultOnCounting: On
  FaultCount: 45
  FaultCountPeriod: 50
  FaultOnImmediate: On
TMASettings:
  AzimuthTimeout: 0.5
  ElevationTimeout: 0.5
  InclinometerDeviationDeg: 2
