#! /bin/sh

### BEGIN INIT INFO
# Provides:        ts-M1M3support
# Required-Start:  $network $remote_fs
# Required-Stop:   $network $remote_fs
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start TS VMS (Vibration Monitor System) daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/sbin

DAEMON=/usr/sbin/ts-M1M3supportd
PIDFILE=/var/run/ts-M1M3supportd.pid

# rcS contains TICKADJ
test -r /etc/default/rcS && . /etc/default/rcS

# Source function library.
. /etc/init.d/functions

# Source devices, export all variables
set -a
. /etc/default/ts-M1M3support
set +a

startdaemon(){
	echo -n "Starting TS M1M3i support:"
	start-stop-daemon --start --oknodo --pidfile ${PIDFILE} --startas $DAEMON -- -p ${PIDFILE} -u m1m3:m1m3
	echo "done"
}
stopdaemon(){
	echo -n "Stopping TS M1M3 support:"
	start-stop-daemon --stop --retry 5 -p ${PIDFILE}
	echo "done"
}

case "$1" in
  start)
	startdaemon
	;;
  stop)
  	stopdaemon
	;;
  restart)
	stopdaemon
	startdaemon
	;;
  status)
	status $DAEMON
	exit $?
	;;
  *)
	echo "Usage: ts-M1M3support { start | stop | status | restart }" >&2
	exit 1
	;;
esac

exit 0
