#ifndef DATATYPES_H_
#define DATATYPES_H_

#include <stdint.h>

#define ACK_INPROGRESS 301
#define ACK_COMPLETE 303
#define ACK_FAILED -302

#define SUBNET_COUNT 5
#define FA_COUNT 156
#define FA_X_COUNT 12
#define FA_Y_COUNT 100
#define FA_Z_COUNT 156
#define HP_COUNT 6
#define HM_COUNT 6
#define BENDING_MODES 22

#define MILLIMETERS_PER_METER 1000.0
#define MICROMETERS_PER_MILLIMETER 1000.0

// SAL__CMD_ACK        300
// SAL__CMD_INPROGRESS 301
// SAL__CMD_STALLED    302
// SAL__CMD_COMPLETE   303
// SAL__CMD_NOPERM    -300
// SAL__CMD_NOACK     -301
// SAL__CMD_FAILED    -302
// SAL__CMD_ABORTED   -303
// SAL__CMD_TIMEOUT   -304

#endif /* DATATYPES_H_ */
