name: test-clang-format

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: './src/LSST ./tests ./src/m1m3sscli.cpp ./src/ts-M1M3supportd.cpp'
        extensions: 'h,cpp'
        clangFormatVersion: 9
        style: file
